{"name": "test_about", "status": "broken", "statusDetails": {"message": "AttributeError: 'async_generator' object has no attribute 'goto'", "trace": "page = <async_generator object page at 0x000001E46D9176B0>\nenv_vars = {'password': 'User@123', 'url': 'https://worldamenities.com/', 'username': 'user123@gmail.com'}\n\n    @pytest.mark.smoke\n    @pytest.mark.asyncio\n    async def test_about(page, env_vars):\n        url = env_vars['url']\n    \n        login_page = LoginPage(page)\n>       await login_page.goto(url)\n\ntests\\test_WAWorld.py:26: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.LoginPage.LoginPage object at 0x000001E46D9486E0>, url = 'https://worldamenities.com/'\n\n    async def goto(self, url: str):\n>       await self.page.goto(url)\nE       AttributeError: 'async_generator' object has no attribute 'goto'\n\npages\\LoginPage.py:28: AttributeError"}, "start": 1720144699477, "stop": 1720144699477, "uuid": "ebb66cba-e3e3-4c02-b8f1-e27ab4746619", "historyId": "b63999fa594676011c2903251915f7b6", "testCaseId": "b63999fa594676011c2903251915f7b6", "fullName": "tests.test_WAWorld#test_about", "labels": [{"name": "tag", "value": "asyncio"}, {"name": "tag", "value": "smoke"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_WAWorld"}, {"name": "host", "value": "Feuji-V005L-R"}, {"name": "thread", "value": "16552-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_WAWorld"}]}